title: Sodya
logo: /Assets/Images/PfpCircle.png
#description: text below image
description: Game Developer | Unity, Blender | C# Coder, 3D Modeler, Animator
show_downloads: false
theme: jekyll-theme-minimal
